seed: 42
device: cuda
dataset:
  name: Thingi10K
  dataset_dir: /workspace/PASDF/dataset/Thingi10K/dataset/pcd
  cls_name: [ 
    "38646","38741","38753","38781","39026","39027",
    "39028","39029","39050","39084","39085","39086",
    "39124","39142","39150","39163","39164","39165",
    "39202","39208"
    ]
  normalize: False
  scale_factor: 1.0
  template_path: data/Thingi10K

infer:
  batch_size: 1
  num_workers: 0
  voxel_size: 0.03
  top_k: 1
  shuffle: False
  cd_threshold: 1.6
  checkpoint_path: results/Thingi10K/runs_sdf/
  output_dir: results/Thingi10K/runs_sdf/outputs
  settings_path: results/Thingi10K/runs_sdf/settings.yaml